name: DisplayMonitor
main: tororo1066.displaymonitor.DisplayMonitor
version: 1.0
api-version: 1.20

softdepend:
  - NMSUtils

libraries:
  - com.ezylang:EvalEx:3.1.2
  - org.jetbrains.kotlin:kotlin-stdlib:1.7.20