name: Create Docs Data

on:
  push:
    branches:
      - master

env:
  GITHUB_USERNAME: ${{ secrets.USERNAME }}
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew GenDocs:shadowJar

      - name: Move Jar to root
        run: mv GenDocs/build/libs/GenDocs.jar GenDocs.jar

      - name: Execute Jar
        run: java -jar GenDocs.jar

      - name: Commit and Push
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs-data.json
          git commit -m "Update docs-data.json"
          git push